.data
.pushsection .hyp.reloc, "a"
.global __hyp_section_.hyp.idmap.text
.word 0
.reloc 0, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xeb8
.word 0
.reloc 4, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xec0
.global __hyp_section_.hyp.text
.global __hyp_section_.hyp.rodata
.word 0
.reloc 8, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3e0
.word 0
.reloc 12, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x400
.word 0
.reloc 16, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x410
.word 0
.reloc 20, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x488
.word 0
.reloc 24, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x490
.word 0
.reloc 28, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x4c8
.word 0
.reloc 32, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x4e8
.word 0
.reloc 36, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x568
.word 0
.reloc 40, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x7e8
.word 0
.reloc 44, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x7f0
.word 0
.reloc 48, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x7f8
.word 0
.reloc 52, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x800
.word 0
.reloc 56, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x808
.word 0
.reloc 60, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x810
.word 0
.reloc 64, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x818
.word 0
.reloc 68, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x820
.word 0
.reloc 72, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x828
.word 0
.reloc 76, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x830
.word 0
.reloc 80, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x838
.word 0
.reloc 84, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x840
.word 0
.reloc 88, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x848
.word 0
.reloc 92, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x850
.word 0
.reloc 96, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x858
.word 0
.reloc 100, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x860
.word 0
.reloc 104, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x868
.word 0
.reloc 108, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x870
.word 0
.reloc 112, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x878
.word 0
.reloc 116, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x880
.word 0
.reloc 120, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x888
.word 0
.reloc 124, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x890
.word 0
.reloc 128, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x898
.word 0
.reloc 132, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x8a0
.word 0
.reloc 136, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x8a8
.word 0
.reloc 140, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x8b0
.word 0
.reloc 144, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x8b8
.word 0
.reloc 148, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1bf8
.word 0
.reloc 152, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c10
.word 0
.reloc 156, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c48
.word 0
.reloc 160, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c60
.word 0
.reloc 164, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c98
.word 0
.reloc 168, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1cb0
.word 0
.reloc 172, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ce8
.word 0
.reloc 176, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d00
.word 0
.reloc 180, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d38
.word 0
.reloc 184, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d50
.word 0
.reloc 188, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d88
.word 0
.reloc 192, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1da0
.word 0
.reloc 196, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1dd8
.word 0
.reloc 200, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1df0
.word 0
.reloc 204, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e28
.word 0
.reloc 208, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e40
.word 0
.reloc 212, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e78
.word 0
.reloc 216, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e90
.word 0
.reloc 220, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ec8
.word 0
.reloc 224, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ee0
.word 0
.reloc 228, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f18
.word 0
.reloc 232, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f30
.word 0
.reloc 236, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f68
.word 0
.reloc 240, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f80
.word 0
.reloc 244, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1fb8
.word 0
.reloc 248, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1fd0
.word 0
.reloc 252, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2008
.word 0
.reloc 256, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2020
.word 0
.reloc 260, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2058
.word 0
.reloc 264, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2070
.word 0
.reloc 268, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x20a8
.word 0
.reloc 272, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x20c0
.word 0
.reloc 276, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x20f8
.word 0
.reloc 280, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2110
.word 0
.reloc 284, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2148
.word 0
.reloc 288, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2160
.word 0
.reloc 292, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2198
.word 0
.reloc 296, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x21b0
.word 0
.reloc 300, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2200
.word 0
.reloc 304, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2238
.word 0
.reloc 308, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2250
.word 0
.reloc 312, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2288
.word 0
.reloc 316, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x22a0
.word 0
.reloc 320, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x22d8
.word 0
.reloc 324, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x22f0
.word 0
.reloc 328, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2340
.word 0
.reloc 332, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2378
.word 0
.reloc 336, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2390
.word 0
.reloc 340, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x23c8
.word 0
.reloc 344, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x23e0
.word 0
.reloc 348, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2430
.word 0
.reloc 352, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2480
.word 0
.reloc 356, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x24b8
.word 0
.reloc 360, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x24d0
.word 0
.reloc 364, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2520
.word 0
.reloc 368, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2570
.word 0
.reloc 372, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x25c0
.word 0
.reloc 376, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x25f8
.word 0
.reloc 380, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2610
.word 0
.reloc 384, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2648
.word 0
.reloc 388, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2660
.word 0
.reloc 392, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x26b0
.word 0
.reloc 396, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2700
.word 0
.reloc 400, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2738
.word 0
.reloc 404, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2750
.word 0
.reloc 408, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2788
.word 0
.reloc 412, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x27a0
.word 0
.reloc 416, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x27f0
.word 0
.reloc 420, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2840
.word 0
.reloc 424, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2878
.word 0
.reloc 428, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2890
.word 0
.reloc 432, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28c8
.word 0
.reloc 436, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28e0
.word 0
.reloc 440, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2918
.word 0
.reloc 444, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2930
.word 0
.reloc 448, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2980
.word 0
.reloc 452, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x29d0
.word 0
.reloc 456, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a20
.word 0
.reloc 460, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a70
.word 0
.reloc 464, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ac0
.word 0
.reloc 468, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2af8
.word 0
.reloc 472, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b10
.word 0
.reloc 476, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b48
.word 0
.reloc 480, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b60
.word 0
.reloc 484, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b98
.word 0
.reloc 488, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2bb0
.word 0
.reloc 492, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c00
.word 0
.reloc 496, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c50
.word 0
.reloc 500, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ca0
.word 0
.reloc 504, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2cf0
.word 0
.reloc 508, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d40
.word 0
.reloc 512, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d78
.word 0
.reloc 516, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d90
.word 0
.reloc 520, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2dc8
.word 0
.reloc 524, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2de0
.word 0
.reloc 528, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e18
.word 0
.reloc 532, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e30
.word 0
.reloc 536, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e68
.word 0
.reloc 540, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e80
.word 0
.reloc 544, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2eb8
.word 0
.reloc 548, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ed0
.word 0
.reloc 552, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f08
.word 0
.reloc 556, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f20
.word 0
.reloc 560, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f58
.word 0
.reloc 564, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f70
.word 0
.reloc 568, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2fa8
.word 0
.reloc 572, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2fc0
.word 0
.reloc 576, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ff8
.word 0
.reloc 580, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3048
.word 0
.reloc 584, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3098
.word 0
.reloc 588, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x30e8
.word 0
.reloc 592, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3100
.word 0
.reloc 596, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3138
.word 0
.reloc 600, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3188
.word 0
.reloc 604, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x31d8
.word 0
.reloc 608, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3228
.word 0
.reloc 612, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3278
.word 0
.reloc 616, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x32c8
.word 0
.reloc 620, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3318
.popsection
